# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('siteid', models.CharField(blank=True, max_length=40, null=True)),
                ('roomid', models.CharField(blank=True, max_length=160, null=True)),
                ('sitename', models.CharField(blank=True, max_length=320, null=True)),
                ('roomname', models.CharField(blank=True, max_length=320, null=True)),
                ('slotid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('weeknumber', models.FloatField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=4000, null=True)),
                ('phone', models.CharField(blank=True, max_length=160, null=True)),
                ('description', models.CharField(blank=True, max_length=523, null=True)),
                ('added', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventData', models.CharField(max_length=10000000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
