# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingevent',
            name='sitename',
        ),
    ]
